parse_config:
  zmk_additional_includes:
    - "modules/zmk/helpers/include"

  zmk_preamble: |
    #include <zmk-helpers/key-labels/42.h>

  raw_binding_map:
    "&sys_reset": Reset
    "&bootloader": Boot
    "&caps_word": Caps Word

    "&bt BT_SEL 0": BT 1
    "&bt BT_SEL 1": BT 2
    "&bt BT_SEL 2": BT 3
    "&bt BT_SEL 3": BT 4
    "&bt BT_CLR": BT Clr

    "&kp LC(INS)": Copy
    "&kp LC(X)": Cut
    "&kp LS(INS)": Paste

    "&smart_mouse": Smart Mouse
    "&smart_num": { "t": "Numword", "s": "Sticky Num" }

    "&quote_morph": { "t": "'", "s": '"' }
    "&comma_morph": { "t": ",", "s": ";" }
    "&dot_morph": { "t": ".", "s": ":" }
    "&slash_morph": { "t": "/", "s": "\\" }
    "&lpar_lt": { "t": "(", "s": "<" }
    "&rpar_gt": { "t": ")", "s": ">" }

    "&de_ae": { "t": "ä", "s": "Ä" }
    "&de_oe": { "t": "ö", "s": "Ö" }
    "&de_ue": { "t": "ü", "s": "Ü" }
    "&de_ss": { "t": "ß", "s": "ẞ" }
    "DE_EURO": "€"
    "&sl INTL": Intl

    "&mmv MOVE_UP": Mouse Up
    "&mmv MOVE_DOWN": Mouse Down
    "&mmv MOVE_LEFT": Mouse Left
    "&mmv MOVE_RIGHT": Mouse Right

    "&msc SCRL_UP": Scroll Up
    "&msc SCRL_DOWN": Scroll Down
    "&msc SCRL_LEFT": Scroll Left
    "&msc SCRL_RIGHT": Scroll Right

    "&mkp LCLK": Left Click
    "&mkp RCLK": Right Click
    "&mkp MCLK": Middle Click

  trans_legend: { "t": "", "type": "trans" }

  zmk_keycode_map:
    LALT: Alt
    RALT: Alt
    LCTRL: Ctrl
    RCTRL: Ctrl
    LGUI: Gui
    RGUI: Gui
    LSHFT: Shift
    RSHFT: Shift

    BSPC: Bspc
    DEL: Del
    ESC: Esc
    RET: Enter
    SPACE: Spc
    TAB: Tab

    PG_UP: PgUp
    PG_DN: PgDn
    INS: Ins
    HOME: Home
    END: End

    UP: Up
    DOWN: Down
    LEFT: Left
    RIGHT: Right

    C_MUTE: Mute
    C_PP: Play
    C_VOL_UP: Vol+
    C_VOL_DN: Vol-
    C_NEXT: Next
    C_PREV: Prev
    C_STOP: Stop

    PSCRN: PrtSc
    SLCK: ScrLk
    CLCK: CapsLk
    KP_NLCK: NumLk
    PAUSE_BREAK: Pause
    K_APP: Menu

    AMPERSAND: "&"
    AMPS: "&"
    APOS: "'"
    APOSTROPHE: "'"
    ASTERISK: "*"
    ASTRK: "*"
    AT: "@"
    BACKSLASH: \
    BSLH: \
    CARET: ^
    COLON: ":"
    COMMA: ","
    DLLR: $
    DOLLAR: $
    DOT: .
    DOUBLE_QUOTES: '"'
    DQT: '"'
    EQUAL: "="
    EXCL: "!"
    FSLH: /
    GRAVE: "`"
    GT: ">"
    HASH: "#"
    LBKT: "["
    LBRC: "{"
    LPAR: (
    LT: <
    MINUS: "-"
    PERCENT: "%"
    PRCNT: "%"
    PIPE: "|"
    PLUS: +
    QMARK: "?"
    RBKT: "]"
    RBRC: "}"
    RPAR: )
    SEMI: ;
    SEMICOLON: ;
    SQT: "'"
    STAR: "*"
    TILDE: "~"
    UNDER: _

  # Override combo drawing for non-adjacent combos
  zmk_combos:
    cut:
      align: top
      dendron: true
      offset: 0.2

draw_config:
  append_colon_to_layer_header: false
  dark_mode: auto
  footer_text: "Toucan Dvorak"
