parse_config:
  zmk_additional_includes:
    - "modules/zmk/helpers/include"

  zmk_preamble: |
    #include <zmk-helpers/key-labels/42.h>

  raw_binding_map:
    "&sys_reset": Reset
    "&bootloader": Boot
    "&caps_word": Caps Word

    "&bt BT_SEL 0": BT 1
    "&bt BT_SEL 1": BT 2
    "&bt BT_SEL 2": BT 3
    "&bt BT_SEL 3": BT 4
    "&bt BT_CLR": BT Clr

    "&kp LC(INS)": Copy
    "&kp LC(X)": Cut
    "&kp LS(INS)": Paste

    "&smart_mouse": Smart Mouse
    "&leader": Leader
    "&leader_sft": Shift+Leader
    "&smart_num NUM 0": { "t": "Numword", "h": "NUM", "s": "Sticky" }
    "&smart_spc NAV 0": { "t": "Spc", "h": "NAV", "s": "Sticky ⇧" }
    "&smart_tab MOUSE 0": { "t": "Tab", "h": "MOUSE", "s": "Del" }
    "&kp SLASH": "/"
    "&lt FUN BSPC": { "t": "Bspc", "h": "FUN" }

    "&de_ae": { "t": "ä", "s": "Ä" }
    "&de_oe": { "t": "ö", "s": "Ö" }
    "&de_ue": { "t": "ü", "s": "Ü" }
    "&de_ss": { "t": "ß", "s": "ẞ" }
    "DE_EURO": "€"
    "&sl MEDIA": { "t": "Media", "type": "layer-activator" }

    "&to BASE": { "t": "Dvorak", "type": "layer-activator" }
    "&to QWERTY": { "t": "Qwerty", "type": "layer-activator" }
    "&to GAME": { "t": "Game", "type": "layer-activator" }
    "&gnum_sft GNUM LSHFT": { "t": "Sticky ⇧", "h": "GNUM", "s": "Hold ⇧" }

    "&mmv MOVE_UP": Mouse Up
    "&mmv MOVE_DOWN": Mouse Down
    "&mmv MOVE_LEFT": Mouse Left
    "&mmv MOVE_RIGHT": Mouse Right

    "&msc SCRL_UP": Scroll Up
    "&msc SCRL_DOWN": Scroll Down
    "&msc SCRL_LEFT": Scroll Left
    "&msc SCRL_RIGHT": Scroll Right

    "&mkp LCLK": Left Click
    "&mkp RCLK": Right Click
    "&mkp MCLK": Middle Click

  trans_legend: { "t": "", "type": "trans" }

  zmk_keycode_map:
    LALT: Alt
    RALT: RAlt
    LCTRL: Ctrl
    RCTRL: Ctrl
    LGUI: Gui
    RGUI: Gui
    LSHFT: Shift
    RSHFT: Shift

    BSPC: Bspc
    DEL: Del
    ESC: Esc
    RET: Enter
    SPACE: Spc
    TAB: Tab

    PG_UP: PgUp
    PG_DN: PgDn
    INS: Ins
    HOME: Home
    END: End

    UP: ↑
    DOWN: ↓
    LEFT: ←
    RIGHT: →

    C_MUTE: $$mdi:volume-off$$
    C_PP: $$mdi:play-pause$$
    C_VOL_UP: $$mdi:volume-high$$
    C_VOL_DN: $$mdi:volume-medium$$
    C_NEXT: $$mdi:skip-forward$$
    C_PREV: $$mdi:skip-backward$$
    C_STOP: $$mdi:stop$$

    PSCRN: PrtSc
    SLCK: ScrLk
    CLCK: CapsLk
    KP_NLCK: NumLk
    PAUSE_BREAK: Pause
    K_APP: Menu

    AMPERSAND: "&"
    AMPS: "&"
    APOS: "'"
    APOSTROPHE: "'"
    ASTERISK: "*"
    ASTRK: "*"
    AT: "@"
    BACKSLASH: \
    BSLH: \
    CARET: ^
    COLON: ":"
    COMMA: ","
    DLLR: $
    DOLLAR: $
    DOT: .
    DOUBLE_QUOTES: '"'
    DQT: '"'
    EQUAL: "="
    EXCL: "!"
    FSLH: /
    GRAVE: "`"
    GT: ">"
    HASH: "#"
    LBKT: "["
    LBRC: "{"
    LPAR: (
    LT: <
    MINUS: "-"
    PERCENT: "%"
    PRCNT: "%"
    PIPE: "|"
    PLUS: +
    QMARK: "?"
    RBKT: "]"
    RBRC: "}"
    RPAR: )
    SEMI: ;
    SEMICOLON: ;
    SQT: "'"
    STAR: "*"
    TILDE: "~"
    UNDER: _

  # Override combo drawing
  zmk_combos:
    combo_cut:
      align: bottom
      offset: 0.15
    combo_ldrsh:
      align: bottom
      dendron: true

draw_config:
  append_colon_to_layer_header: false
  dark_mode: auto
  shrink_wide_legends: 6
  footer_text: "Toucan Endgame"
