name: Build ZMK firmware (nix)
on:
  workflow_dispatch:
  push:
    paths:
      - config/**
      - build.yaml
      - zmk-keyboard-toucan/**

jobs:
  build:
    uses: ecoughlan/zmk-actions/.github/workflows/build-user-config.yml@main
    with:
      # ZMK Studio requires 'zephyr-full' toolchain
      toolchain: zephyr-full
